![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# Pandas Series exercises


In [1]:
# Import the numpy package under the name np
import numpy as np

# Import the pandas package under the name pd
import pandas as pd

# Print the pandas version and the configuration
print(pd.__version__)

1.1.5


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series creation

### Create an empty pandas Series

In [2]:
# your code goes here
pd.Series()

/home/pkg/Downloads/tut/.venv/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  


Series([], dtype: float64)

In [3]:
pd.Series()

/home/pkg/Downloads/tut/.venv/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  """Entry point for launching an IPython kernel.


Series([], dtype: float64)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y pandas Series

In [9]:
# your code goes here
x =[i for i in range(10)]
y = pd.Series(x)
y

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [ ]:
X = ['A','B','C']
print(X, type(X))

Y = pd.Series(X)
print(Y, type(Y)) # different type

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, name it 'My letters'

In [11]:
# your code goes here
y.name = 'My letters'
y

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
Name: My letters, dtype: int64

In [ ]:
X = pd.Series(['A','B','C'])

X.name = 'My letters'
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show its values


In [15]:
# your code goes here
y.index


RangeIndex(start=0, stop=10, step=1)

In [ ]:
X = pd.Series(['A','B','C'])

X.values

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series indexation

### Assign index names to the given X pandas Series


In [19]:
# your code goes here
index_name = ['A','B','C','D','E','F','G','H','I','J']
y.index = index_name
y

A    0
B    1
C    2
D    3
E    4
F    5
G    6
H    7
I    8
J    9
Name: My letters, dtype: int64

In [ ]:
X = pd.Series(['A','B','C'])
index_names = ['first', 'second', 'third']

X.index = index_names
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show its first element


In [20]:
# your code goes here
y.iloc[0]

0

In [ ]:
X = pd.Series(['A','B','C'], index=['first', 'second', 'third'])

#X[0] # by position
#X.iloc[0] # by position
X['first'] # by index

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show its last element


In [21]:
# your code goes here
y.iloc[-1]

9

In [ ]:
X = pd.Series(['A','B','C'], index=['first', 'second', 'third'])

#X[-1] # by position
#X.iloc[-1] # by position
X['third'] # by index

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show all middle elements


In [22]:
# your code goes here
y.iloc[1:-1]

B    1
C    2
D    3
E    4
F    5
G    6
H    7
I    8
Name: My letters, dtype: int64

In [ ]:
X = pd.Series(['A','B','C','D','E'],
              index=['first','second','third','forth','fifth'])

#X[['second', 'third', 'forth']]
#X.iloc[1:-1] # by position
X[1:-1] # by position

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the elements in reverse position


In [23]:
# your code goes here
y.iloc[::-1]

J    9
I    8
H    7
G    6
F    5
E    4
D    3
C    2
B    1
A    0
Name: My letters, dtype: int64

In [ ]:
X = pd.Series(['A','B','C','D','E'],
              index=['first','second','third','forth','fifth'])

#X.iloc[::-1]
X[::-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the first and last elements


In [24]:
# your code goes here
y.iloc[[0,-1]]

A    0
J    9
Name: My letters, dtype: int64

In [ ]:
X = pd.Series(['A','B','C','D','E'],
              index=['first','second','third','forth','fifth'])

#X[['first', 'fifth']]
#X.iloc[[0, -1]]
X[[0, -1]]

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series manipulation

### Convert the given integer pandas Series to float


In [27]:
# your code goes here
x = pd.Series(y,dtype = np.float)
x

A    0.0
B    1.0
C    2.0
D    3.0
E    4.0
F    5.0
G    6.0
H    7.0
I    8.0
J    9.0
Name: My letters, dtype: float64

In [ ]:
X = pd.Series([1,2,3,4,5],
              index=['first','second','third','forth','fifth'])

pd.Series(X, dtype=np.float)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given pandas Series (first element becomes last)

In [31]:
# your code goes here
x = x.iloc[::-1]
x

J    9.0
I    8.0
H    7.0
G    6.0
F    5.0
E    4.0
D    3.0
C    2.0
B    1.0
A    0.0
Name: My letters, dtype: float64

In [ ]:
X = pd.Series([1,2,3,4,5],
              index=['first','second','third','forth','fifth'])

X[::-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given pandas Series


In [32]:
# your code goes here
x.sort_values()

A    0.0
B    1.0
C    2.0
D    3.0
E    4.0
F    5.0
G    6.0
H    7.0
I    8.0
J    9.0
Name: My letters, dtype: float64

In [ ]:
X = pd.Series([4,2,5,1,3],
              index=['forth','second','fifth','first','third'])

X = X.sort_values()
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, set the fifth element equal to 10


In [38]:
# your code goes here

x = x.sort_values()
x.iloc[4] = 10
x

A     0.0
B     1.0
C     2.0
D     3.0
I    10.0
J     9.0
H    10.0
G    10.0
E    10.0
F    10.0
Name: My letters, dtype: float64

In [ ]:
X = pd.Series([1,2,3,4,5],
              index=['A','B','C','D','E'])

X[4] = 10
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, change all the middle elements to 0


In [39]:
# your code goes here
x.iloc[1:] = 0
x

A    0.0
B    0.0
C    0.0
D    0.0
I    0.0
J    0.0
H    0.0
G    0.0
E    0.0
F    0.0
Name: My letters, dtype: float64

In [ ]:
X = pd.Series([1,2,3,4,5],
              index=['A','B','C','D','E'])

X[1:-1] = 0
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, add 5 to every element


In [40]:
# your code goes here
x+5

A    5.0
B    5.0
C    5.0
D    5.0
I    5.0
J    5.0
H    5.0
G    5.0
E    5.0
F    5.0
Name: My letters, dtype: float64

In [ ]:
X = pd.Series([1,2,3,4,5])

X + 5

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series boolean arrays (also called masks)

### Given the X pandas Series, make a mask showing negative elements


In [42]:

# your code goes here
x = np.random.randn(10)
m = x<0
x[m]

array([-1.62690013, -0.3473045 , -0.45488745, -0.95680844])

In [ ]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get the negative elements


In [43]:
# your code goes here
print(x)
print(m)
print(x[m])

[ 1.10420209 -1.62690013 -0.3473045   1.0726126   1.70620744  0.49700156
 -0.45488745  0.14978263 -0.95680844  1.18316181]
[False  True  True False False False  True False  True False]
[-1.62690013 -0.3473045  -0.45488745 -0.95680844]


In [ ]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
X[mask]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get numbers higher than 5


In [46]:
# your code goes here
x = np.random.randint(100,size = 10)
print("{}\n\n".format(x))
mask  = x>5
x[m]

[ 2  6 71  9  1 26  4  3  6 53]




array([ 6, 71,  4,  6])

In [ ]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = X > 5
X[mask]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get numbers higher than the elements mean

In [60]:
# your code goes here
x = np.random.randint(1000,size = 25)
print("{}\n".format(x))
mask = x>x.mean()
x[mask]


[351 467 775 695 698 523 682 921 514 795 125 655 131 446 155 503 581 696
 914 686 475 312  56 280 373]



array([775, 695, 698, 523, 682, 921, 514, 795, 655, 581, 696, 914, 686])

In [ ]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = X > X.mean()
X[mask]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get numbers equal to 2 or 10


In [64]:
# your code goes here
x  = np.random.randint(15,size = 20)
mask = (x==2)| (x==10)
x[mask]

array([10, 10, 10, 10])

In [ ]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = (X == 2) | (X == 10)
X[mask]

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions

### Given the X pandas Series, return True if none of its elements is zero

In [70]:
# your code goes here
x.any()
x

array([14, 10, 14,  4,  8, 13,  9, 12, 10,  7,  8,  3,  6, 10, 10, 12,  1,
        5,  8,  7])

In [74]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

X.all()

False

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, return True if any of its elements is zero


In [78]:
# your code goes here
x.any()
type(x)

numpy.ndarray

In [73]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

X.any()

True

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X pandas Series, show the sum of its elements


In [79]:
x.sum()

171

In [80]:
X = pd.Series([3,5,6,7,2,3,4,9,4])

#np.sum(X)
X.sum()

43

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the mean value of its elements

In [81]:
# your code goes here
x.mean()

8.55

In [ ]:
X = pd.Series([1,2,0,4,5,6,0,0,9,10])

#np.mean(X)
X.mean()

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the max value of its elements

In [83]:
# your code goes here
x.max()

14

In [84]:
X = pd.Series([1,2,0,4,5,6,0,0,9,10])

#np.max(X)
X.max()

10

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)